[package]
name = "wasm-collision-detection"
version = "0.1.0"
authors = ["benc <ben.clare2@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
cgmath = "0.17"
