version: "3"

services:
    webapp:
        build:
            context: .
        image: webapp:latest
        ports: 
            - 8080:8080

    database:
        image: mongo:latest
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
