name = "todos"
type = "javascript"
account_id = "b3f0acbc711e4284bf57bfc33bf46bbb"
workers_dev = true
route = ""
zone_id = ""

kv-namespaces = [ 
         { binding = "TODOS", id = "612f4c40e42848b8b238d1b85f03c30a" } 
]
