AWSTemplateFormatVersion : '2010-09-09'
Description: ApiGatewayWss

Parameters:
  DomainName:
    Type: String
    Default: experiment.bens-stuff.net

Resources:
    DomainCertificate:
        Type: 'AWS::CertificateManager::Certificate'
        Properties:
          DomainName: !Ref DomainName

    Domain:
        Type: AWS::ApiGateway::DomainName
        Properties:
            DomainName: !Ref DomainName
            CertificateArn: !Ref DomainCertificate

    ApiGateway:
        Type: AWS::ApiGatewayV2::Api
        Properties:
            Name: WssGateway
            ProtocolType: WEBSOCKET
            RouteSelectionExpression: ${request.body.action}

    ProdStage:
        Type: AWS::ApiGatewayV2::Stage
        Properties:
            StageName: Prod
            Description: Prod Stage
            ApiId: !Ref ApiGateway

    ApiMapping:
        Type: AWS::ApiGatewayV2::ApiMapping
        Properties:
            DomainName: !Ref Domain
            ApiId: !Ref ApiGateway
            Stage: !Ref ProdStage