
version: "3"
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        working_dir: /
        environment: 
            PORT: 8080
            NODE_ENV: "production"
        volumes:
            - "./__sapper__/build:/__sapper__/build"
        ports:
            - "8080:8080"
        command: node build
