[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["benc <ben.clare2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[lib]
proc-macro = true
